server:
    port: ${COLLECTOR_OUTBOX_PORT:9999}
spring:
    application:
        name: collector-outbox
    profiles:
        active: ${COLLECTOR_OUTBOX_PROFILE:dev}
    main:
        banner-mode: ${COLLECTOR_OUTBOX_BANNER:off}
        allow-bean-definition-overriding: ${SPRING_MAIN_ALLOW_BEAN_DEF_OVERRIDING:true}
logging:
    level:
        root: INFO
        org.springframework: ERROR
        org.apache.http.wire: ERROR
        org.elasticsearch.client.RestClient: INFO
        org.apache.camel.component.elasticsearch: INFO
        org.elasticsearch.client.sniff.Sniffer: OFF
camel:
    springboot:
        main-run-controller: ${SPRING_MAIN_RUN_CONTROLLER:true}